#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PYTHONPATH=$DIR

PYTHON3="$DIR/external/bin/python3.5"
if [ ! -f "$PYTHON3" ]; then
    PYTHON3=python3
fi

exec "$PYTHON3" -m game
